# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.13.5
    working_directory: /go/src/github.com/HewlettPackard/hpecli
    steps:
      - checkout
      - run: mkdir -p coverage/go/coverage.out
      - run: go get -v -t -d ./...
      - run: go test ./... -short -coverprofile=coverage/go/coverage.out
      - run: ./build.sh
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud